name: Create Tokens
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer sd-input/src/figma-tokens-output.json sd-tokens/button.json button
      # Create a light theme, exclude the global tokens
      - run: npx token-transformer sd-input/src/figma-tokens-output.json sd-tokens/typography.json typography button,spacing
      # Create a dark theme, exclude the global tokens
      - run: npx token-transformer sd-input/src/figma-tokens-output.json sd-tokens/spacing.json spacing button,typography
      # Convert tokens according to Style Dictionary config
      - run: node build.cjs
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens